-- Create countries table
CREATE TABLE IF NOT EXISTS countries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,
  code TEXT NOT NULL UNIQUE, -- ISO country code (US, GB, etc.)
  region TEXT NOT NULL, -- Europe, Asia, Americas, etc.
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert common countries
INSERT INTO countries (name, code, region) VALUES
  ('United States', 'US', 'Americas'),
  ('United Kingdom', 'GB', 'Europe'),
  ('Germany', 'DE', 'Europe'),
  ('France', 'FR', 'Europe'),
  ('Japan', 'JP', 'Asia'),
  ('Australia', 'AU', 'Oceania'),
  ('Canada', 'CA', 'Americas'),
  ('Spain', 'ES', 'Europe'),
  ('Italy', 'IT', 'Europe'),
  ('Netherlands', 'NL', 'Europe'),
  ('Switzerland', 'CH', 'Europe'),
  ('Austria', 'AT', 'Europe'),
  ('Belgium', 'BE', 'Europe'),
  ('Portugal', 'PT', 'Europe'),
  ('Sweden', 'SE', 'Europe'),
  ('Norway', 'NO', 'Europe'),
  ('Denmark', 'DK', 'Europe'),
  ('Finland', 'FI', 'Europe'),
  ('South Korea', 'KR', 'Asia'),
  ('Singapore', 'SG', 'Asia'),
  ('Thailand', 'TH', 'Asia'),
  ('Malaysia', 'MY', 'Asia'),
  ('Indonesia', 'ID', 'Asia'),
  ('Philippines', 'PH', 'Asia'),
  ('Vietnam', 'VN', 'Asia'),
  ('India', 'IN', 'Asia'),
  ('China', 'CN', 'Asia'),
  ('Hong Kong', 'HK', 'Asia'),
  ('Taiwan', 'TW', 'Asia'),
  ('New Zealand', 'NZ', 'Oceania'),
  ('Brazil', 'BR', 'Americas'),
  ('Mexico', 'MX', 'Americas'),
  ('Argentina', 'AR', 'Americas'),
  ('Chile', 'CL', 'Americas'),
  ('Colombia', 'CO', 'Americas'),
  ('Peru', 'PE', 'Americas'),
  ('South Africa', 'ZA', 'Africa'),
  ('Egypt', 'EG', 'Africa'),
  ('Morocco', 'MA', 'Africa'),
  ('Kenya', 'KE', 'Africa'),
  ('Nigeria', 'NG', 'Africa'),
  ('Ghana', 'GH', 'Africa'),
  ('Turkey', 'TR', 'Europe'),
  ('Russia', 'RU', 'Europe'),
  ('Ukraine', 'UA', 'Europe'),
  ('Poland', 'PL', 'Europe'),
  ('Czech Republic', 'CZ', 'Europe'),
  ('Hungary', 'HU', 'Europe'),
  ('Romania', 'RO', 'Europe'),
  ('Bulgaria', 'BG', 'Europe'),
  ('Croatia', 'HR', 'Europe'),
  ('Slovenia', 'SI', 'Europe'),
  ('Slovakia', 'SK', 'Europe'),
  ('Lithuania', 'LT', 'Europe'),
  ('Latvia', 'LV', 'Europe'),
  ('Estonia', 'EE', 'Europe'),
  ('Ireland', 'IE', 'Europe'),
  ('Iceland', 'IS', 'Europe'),
  ('Luxembourg', 'LU', 'Europe'),
  ('Malta', 'MT', 'Europe'),
  ('Cyprus', 'CY', 'Europe'),
  ('Greece', 'GR', 'Europe'),
  ('Israel', 'IL', 'Asia'),
  ('United Arab Emirates', 'AE', 'Asia'),
  ('Saudi Arabia', 'SA', 'Asia'),
  ('Qatar', 'QA', 'Asia'),
  ('Kuwait', 'KW', 'Asia'),
  ('Bahrain', 'BH', 'Asia'),
  ('Oman', 'OM', 'Asia'),
  ('Jordan', 'JO', 'Asia'),
  ('Lebanon', 'LB', 'Asia')
ON CONFLICT (code) DO NOTHING;

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_countries_code ON countries(code);
CREATE INDEX IF NOT EXISTS idx_countries_region ON countries(region);
